task:
  samples_root: 'artifacts/samples'
  lr: ${learning_rate}
  timesteps: 1000
  loss_type: 'l2'
  loss_keys:
      - 'diffusion_loss'
  frame_threshold: 0.5
  beta_start: 0.0001
  beta_end: 0.02
  training:
      mode: 'x_0' # either 'x_0' or epsilon
  sampling:
      type: 'cfdg_ddpm_x0'
      w: 0