task:
  samples_root: 'artifacts/samples'
  lr: ${learning_rate}
  timesteps: 1000
  loss_type: 'l1'
  loss_keys:
      - 'diffusion_loss'
      - 'tempo_vel_loss'
  beta_start: 0.0001
  beta_end: 0.2
  training:
      mode: 'epsilon' # either 'x_0' or epsilon
  sampling:
      type: 'cfdg_ddpm'
      w: 1.2
  sample_steps_frac: ${test.sample_steps_frac}
  transfer: ${test.transfer}
